### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by PECM4N**

### CODE REVIEW

**Comment by PECM4N** [comment]
comments?

**Comment by wwchu11** [comment]
SHARKS

**Comment by PECM4N** [comment]
you wot m8

**Comment by wwchu11** [comment]
[sdfgsf.txt](https://github.com/rgmerk/FIT2099-Assignment-1/files/927310/sdfgsf.txt)

**Comment by kpet26** [comment]
hey, do you guys want to meet up to do the assignment? we can do the work breakdown agreement and work on the general structure of our design

**Comment by kpet26** [comment]
also before meeting up, we should go over the assignment requirements and by ourselves work out how we would design the code by ourselves and then we can discuss how to write everything up

**Comment by wwchu11** [comment]
wait your with us?

**Comment by PECM4N** [comment]
I don't know what's happened, but were you assigned to a group recently? As far as we knew we signed up as a group of two, and we have already started and distributed the work. You're welcome to join us, but it's a bit of a surprise that the tutors/lecturers have given us no notification of this. Anyway, if this isn't a system glitch and you are joining our group, in regards to your question, we generally just use a voice chat to communicate. Last time we used the steam voice chat.

Hopefully you can inform us of whats going on :P

**Comment by kpet26** [comment]
hey, wow how weird.. Yeah they assigned me to your group and I thought we
were all placed together as a new group...

**Comment by kpet26** [comment]
how strange

**Comment by wwchu11** [comment]
So far this is our WBA before you're assigned to us.

Wilson:
-Producing deliverable
-Completion of deliverables

Harry:
-Testing/reviewing
-Completion of deliverables

So yea the both of us were doing the completion of deliverables at the same time. Take a pick, which role would you go for so I can remake the WBA. And as meeting for assignment, do you have steam or any other voice chat application as well as a mic? Atm voice chatting seems perfect and convenient.

**Comment by kpet26** [comment]
honestly, I do not want to interrupt anything that you guys wanted to do.. so you can pass me anything and I will do it 

I don't have steam (I know, worst game dev student ever) but I can get it and I have skype etc so Im pretty chill

**Comment by wwchu11** [comment]
img_1173
img_1170

**Comment by wwchu11** [comment]
kpet we will give you the role of reviewing our diagrams, Harry will be uploading the rest here. We could all do voice chat on this weekend if your confused with our diagram. Don't mind my messy diagram tho since I'll redraw them properly again after you've reviewed them all.

**Comment by PECM4N** [comment]
cci22042017
This is part of the droid section. A lot of it is missing I know (and what's there is probs wrong), and there's a lot more that has to be added on other forms, that share with the other tasks, which we will have to meet up to work on together probably.

**Comment by kpet26** [comment]
Hey, you can call me Kim haha

To make life easier to contact me, add me on fb Kimberley Petryshyn if you
want

sure i will review the diagrams and try to implement some of it on eclipse

I am working all of tomorrow so I can have a full look at it tomorrow night
and then do you want to chat about it on sunday?

let me know if that is an issue? :)

**Comment by wwchu11** [comment]
Yuh sunday's good, we could talk about why we made the diagram the way it already was and its purpose.

**Comment by PECM4N** [comment]
Hey ppls, did we still want to discuss the project tomorrow? If so what time? I have a bit on, but I am free from about 1-5pm and 7:30pm onwards.

**Comment by kpet26** [comment]
best for me is 7:30 onwards but still can try to do arvo if need be

**Comment by PECM4N** [comment]
Btw Wilson and I are also planning to meet at tomorrows consultation to discuss the assignment as well. might be easier than tonight if you are free then. That way we don't have to mess around with some kind of voice chat that we all have.

**Comment by kpet26** [comment]
yeah sure ill be there

**Pull request closed without merging**
